services:
  x_test_service:
    container_name: service_test_container
    env_file:
      - .launch/tests/.test_env
    build:
        context: ./
        dockerfile: .launch/tests/api/Dockerfile
    command: >
      bash -c "sleep 10 && alembic upgrade head && pytest --cov=. tests/"
    volumes:
      - ./:/app
    depends_on:
      - x_test_redis_service
      - x_test_rabbit_mq_service
      - x_test_psql_db_service

  x_test_psql_db_service:
    image: postgres:latest
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: test_db
    ports:
      - "5450:5432"
    healthcheck:
      test: ["CMD-SHELL", "set PGPASSWORD=dev && pg_isready -d test_db -U dev"]
      interval: 2s
      timeout: 10s
      retries: 10
    env_file:
      - ./.launch/tests/.test_env

  x_test_rabbit_mq_service:
    image: rabbitmq:3.11.6-management
    ports:
      - "5682:5672"
    environment:
      RABBITMQ_DEFAULT_USER: dev
      RABBITMQ_DEFAULT_PASS: dev

  x_test_redis_service:
    image: redis:latest
    ports:
      - "6382:6379"
