# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: debug.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'debug.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x64\x65\x62ug.proto\x12\rgrpc.pb.debug\x1a\x19google/protobuf/any.proto\"\x0f\n\rSayMeqDataReq\"*\n\x0bTestDataReq\x12\x0c\n\x04year\x18\x01 \x01(\t\x12\r\n\x05month\x18\x02 \x01(\t\"?\n\nMessageReq\x12\r\n\x05\x65vent\x18\x01 \x01(\t\x12\"\n\x04\x64\x61ta\x18\x02 \x01(\x0b\x32\x14.google.protobuf.Any\".\n\x0bMessageResp\x12\x0e\n\x06status\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2V\n\x0c\x44\x65\x62ugService\x12\x46\n\x0bSendMessage\x12\x19.grpc.pb.debug.MessageReq\x1a\x1a.grpc.pb.debug.MessageResp\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'debug_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SAYMEQDATAREQ']._serialized_start=57
  _globals['_SAYMEQDATAREQ']._serialized_end=72
  _globals['_TESTDATAREQ']._serialized_start=74
  _globals['_TESTDATAREQ']._serialized_end=116
  _globals['_MESSAGEREQ']._serialized_start=118
  _globals['_MESSAGEREQ']._serialized_end=181
  _globals['_MESSAGERESP']._serialized_start=183
  _globals['_MESSAGERESP']._serialized_end=229
  _globals['_DEBUGSERVICE']._serialized_start=231
  _globals['_DEBUGSERVICE']._serialized_end=317
# @@protoc_insertion_point(module_scope)
