# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: example.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(_runtime_version.Domain.PUBLIC, 5, 29, 0, "", "example.proto")
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\rexample.proto\x12\rgrpc.messages" \n\nExampleReq\x12\x12\n\nexample_id\x18\x01 \x01(\x05"&\n\x0b\x45xampleResp\x12\x17\n\x0f\x65xample_message\x18\x01 \x01(\t2W\n\x0e\x45xampleService\x12\x45\n\nGetExample\x12\x19.grpc.messages.ExampleReq\x1a\x1a.grpc.messages.ExampleResp"\x00\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "example_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_EXAMPLEREQ"]._serialized_start = 32
    _globals["_EXAMPLEREQ"]._serialized_end = 64
    _globals["_EXAMPLERESP"]._serialized_start = 66
    _globals["_EXAMPLERESP"]._serialized_end = 104
    _globals["_EXAMPLESERVICE"]._serialized_start = 106
    _globals["_EXAMPLESERVICE"]._serialized_end = 193
# @@protoc_insertion_point(module_scope)
